### ISSUE TITLE
consider using config.site

### ISSUE THREAD

**Issue by egberts** [egberts/easy-admin#1]
Instead of having many-distro logic in multiple bash scripts, consider using autotool `config.site`. 

reference : https://stackoverflow.com/a/46869388/4379130

**Comment by egberts** [comment]
Redhat insisted that `config.site` is ONLY for `/usr`.

Documentation is poor so we don't know if this file is for templating toward an alternative `--prefix` or not.  

https://bugzilla.redhat.com/show_bug.cgi?id=1510073

**Comment by egberts** [comment]
Also there is some more issues on configure `--libdir` option with `config.site` file.  

https://stackoverflow.com/questions/47124066/incorrect-libdir-when-building-pc-using-config-site

**Comment by egberts** [comment]
More fights over original maintainers' intent of `--libdir=` versus distro packagers use of `--prefix`. 

https://stackoverflow.com/questions/46847939/config-site-for-vendor-libs-on-fedora-x86-64?rq=1

**Comment by egberts** [comment]
CentOS is a "`WONTFIX`" on `config.site`.

But a guided template from Fedora's copy of `config.site` should work for that CentOS distro in this repository here. 

https://bugzilla.redhat.com/show_bug.cgi?id=772997

**Comment by egberts** [comment]
Autotool states that the `config.site` file is the responsibility of the distro (Redhat). 

Yet, Redhat seems indifferent to autotool because they think their RPM can cover adequately the situations for imported libraries (but it has to be in just THEIR RPM library package).

So, CentOS is increasingly becoming unfriendly toward non-RPM packages.  

Excerpt from Autotool:
> If the environment variable `CONFIG_SITE` is set, configure uses its value as a space-separated list of shell scripts to read; it is recommended that these be absolute file names. Otherwise, it reads the shell script `prefix/share/config.site` if it exists, then `prefix/etc/config.site` if it exists. Thus, settings in machine-specific files override those in machine-independent ones in case of conflict.

https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.71/autoconf.html#Site-Defaults

**Comment by egberts** [comment]
As the original stakeholder and shareholder of Red … Hat (thanks, Alex. Brown Deutsche Bank for the easy life), I can call them anything I like. It’s legacy that I am referring on to.

Opinions of RH maintainers that shapes the flow of acceptance of the company by end-users, got it.  I could file another CentOS bug but the new board will probably just put “their thumb on the scale”.

**Comment by praiskup** [comment]
The info how to report bugs is here:
https://wiki.centos.org/ReportBugs

The thing is—it will be very hard or maybe impossible to install anything
into `/usr/local` using a supported Fedora/RHEL package:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_no_files_or_directories_under_srv_usrlocal_or_homeuser
The practice can be seen here (Fedora 36 pre-release):
```
sudo dnf install /usr/local/'*'
[sudo] password for praiskup: 
Last metadata expiration check: 1:36:29 ago on Fri 25 Mar 2022 06:09:22 AM CET.
Package filesystem-3.16-2.fc36.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Or what prefix do you actually want to handle?  If the default `/usr`, then it should be already
done, no?  Minus EL 7 where, in this production cycle, is unlikely to get anything non-critical.

**Comment by egberts** [comment]
> alright. I just sooner like to see CentOS stop losing share to RockyOS, this would be a small thing that would make CentOS a bit more inclusive.

And CentOS is going, going gone!

**Comment by egberts** [comment]
Related link: https://bugzilla.redhat.com/show_bug.cgi?id=1510073
